---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    app.kubernetes.io/name: local-path-provisioner
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

