apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# This overlay is static and does not change per cluster
# The global-config ConfigMap is created by Ansible directly in the cluster
# The base kustomization uses replacements to reference it
